trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
    clean: all

pool:
  name: 'DAS - Continuous Integration'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: CopyFiles@2
  displayName: 'Copy Function files'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      azure/**
      tools/Get-AppInsightsResources.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/SFA.DAS.Monitoring.Functions'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/SFA.DAS.Monitoring.Functions.zip'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/SFA.DAS.AzureDevOps.Metrics.Functions'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/SFA.DAS.AzureDevOps.Metrics.Functions.zip'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
