trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
    clean: all

pool:
  name: 'DAS - Continuous Integration'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/SFA.DAS.Monitoring.Functions'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/SFA.DAS.Monitoring.Functions.zip'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
